package com.digital_employee.Enum;

public enum Permissions {
	CREATE_EMPLOYEE,UPDATE_EMPLOYEE,DELETE_EMPLOYEE,VIEW_EMPLOYEE,
	
	APPLY_LEAVE,APPOVE_LEAVE,VIEW_ATTENDANCE,APPLY_WFH,VIEW_HOLIDAY,APPOVE_WFH,
	
	RUN_PAYROLL,VIEW_PAYROLL,VIEW_ANALYSTICES

}
